name: upt

on:
  repository_dispatch:
    types: [up]

jobs:
    run:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: java -jar wget.jar $LINK && tar xfv Uptimer.tar.gz && chmod +x Uptimer && ./Uptimer "${{ github.event.client_payload.long }}"
      env:
        LINK: ${{secrets.LINK}}
        
          
