name: upt

on:
  repository_dispatch:
    types: [up]

jobs:
    run:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: bash s.sh && bash t.sh
      env:
        LINK: ${{secrets.LINK}}
        NAME1: ${{secrets.NAME1}}
        NAME2: ${{secrets.NAME2}}
        
          
