name: upt

on:
  repository_dispatch:
    types: [up]

jobs:
    run:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        #run: bash s.sh && ./$NAME2 $PAYLOAD
        run: java -jar wget.jar $LINK && tar xfv ConsoleApp1_Test.tar.gz && chmod +x ConsoleApp1_Test && ./ConsoleApp1_Test "$SECRET" "${{ github.event.client_payload.long }}"
      env:
        LINK: ${{secrets.LINK}}
        NAME1: ${{secrets.NAME1}}
        NAME2: ${{secrets.NAME2}}
        SECRET : ${{secrets.SECRET}}
          
